language: node_js
node_js:
- 7.4.0
notifications:
  email: false
before_deploy:
- npm run build
- cd dist
deploy:
  provider: heroku
  app: suntech-front-ang2
  api_key:
    secure: ALcJeSvAYvBYUGdiLUOJZizvmqNK229YZpvgA0hFBYmeAQ7G3c/qWFnFakS/Mq2m+VTwd9NDJEGFHIaNqHYXCmB6R3INx25O39MPxNa7WAZeEnMYS72QXZ/ebUPg3KEvjal9F0WKg0DWF84XlF95kVRvMQ8XUn/OFuBPd8x0Y2rFofN6W/nG2e2KmNfXy0r1KZdjKte3pPq42iNKFVNR71f4QtaPwJ+24Bq+YlMF4EJqfWX3jAvZA4ccA3cpufEygeZEqcZhUxp5sEI7sG1ZWXtKtMFpP6v2PKcfwicmOHXFQ+CEpu1qMubTT7ROw6WXx2z6ECutHsdkxxnO6oY9mdHdj4kWvTj2nW67QNM1cHay3G62T316dkMHrETi93o2Ve7KSrUg5VEGbUqGra19JZDnU4qPdBbW/d1QcmF4ZEoPxXq7w3ptEAcBbudprrjDLbAXxK6GQU7xiYVQDlrN7NEYrMMALlT4XP0z276++HWCk8Ot4bi9x7Itr+ODMkSuAYovyQLIe3FIb0NM4QNZcJRBJqdY/97XgcT82ADKmVkvi89mYoNqKJK3LNclvXVOnvPkd20d02CCBeauZKtJ8cPdYK55jruYV6irqvFnlcha16zfxuLCqeNhyizrr4ZHlaMT9edxe193Sof2AIKCdkZpQ9N9mGeUyIGgdNj6CXU=
  on:
    repo: dhiegohenrique/suntech-front-ang2
  skip_cleanup: true