language: node_js
node_js:
- 7.4.0
notifications:
  email: false
before_deploy:
- npm run build
- cd dist
deploy:
  provider: heroku
  api_key:
    secure: CyyPncZCeXp+1LjAmxLsR6BaGAUg0Q0C1D0lzbIc+3diIULHFShQYSsr3SThGgsxV5lALFSvoIFrmh9F15B/gXs/EEbyNOEQF5N2BnZePPp8xMmDZnOb/1InjSfMmwBR2g5eOrZR7huoIcA0IgPz99GMuJSdF8UqYpzrKQxZ9XolnK7vzs5RoMOE2VY5tvEfJrGNXh6pe8j5r/pKYXB60KTzZDUee3BDG1c1QhhrLNJ8s7EIFeYzFxWuh/LHnnJNBwYawfK1oyjl+hVZanfgCqg0q9MQV6NMOVLvos4KCfTprsTZJR0AUIpjV/wZmJH2Wp/VSazFPa8s006HY1FwEoSEtA3w5l+tnVw9bz5erB9c1/jXCGHE8qooGifAGsgZ1WQwWDFexSgc9vU4nfdwa8dmN300EH+mojBu3TnViR1gyER7P2TJH4xnsWtjCIcWsyq+J1VC0bgwpN4hfLB9tjhsqYwVxNrFqzDQWgzNdIY6IpRHx1jS+ECSXKNTkUMBrbq7Kgx38rSFVxDDuyQes3MiFUJT8F1Y6ppF2fr//01IZ33HK405L+naHt1TqrvJd5HPOezimmf7GGBYqBIGD5ugdr9wrm/Ry0VRnPe+BlH6xFjsdUQ0p9AjRYTIpVPr9N0B5iCuY3iXNPM7/kgkSPu0GdVYb74nzMoc5IKeHEE=
  app: suntech-front-ang2
  on:
    repo: dhiegohenrique/suntech-front-ang2
